install:
  - sudo apt-get update
  - sudo apt-get install libmagick++-dev
  - gem install rmagick exifr

script:
  - cd docs; bundle install; bundle exec jekyll build; touch ./_site/.nojekyll; cd ..

deploy:
  - provider: pages
    github-token:
      secure: "e8eHPIPJIxaBJQtkS2qhuZpMpcQRlnzP3vCJ2xAIPWsHdI4EOlROFK6Ck0HxkGd30GFAgC0S/32pyie76q2b3BVR0J4rnK1wj8NtQ4Yt6JO4xXdf2KlShktPcPfeNdsJzp+C6h+eKf1FY2V1VlUJe5XRnCRfZ5rQf9YCUfCqFsJqgsIADF2ZkeMbhMojaSRlXbB4uApCEFUGEbZ9p8L7rXdE5g1l954E/KmG80rKh4XsoFU9IYCEgRhVZOktTZs0oywbv3ohA2xBDZddfi4Bqhll86xMln/6Fp3K5gTO51arIrBjHQbIPX9ZgXn9RQ5tL04dDogkZRzO8Lx3N1VsUFqnWcXKrl2+n9PF3tx8KRBwTdf/R0rfjBco8+76M2arzI86vUr7S5keDDlqddPDzRpikmePqVUkvDJZknQonrvn6b7k4pIfHQ7UJBmqP9U5IMv6QOMLIgBxs821tq9l0c71iEYSagDrD9tcO1kD6+W5WKNMcaS8/TPLIp4KM+5crO+mqzB8urFYDgcbUE3KlXhxEG2u5LYhoF4fw2VJPrCY5NaZh4ZzzAziu6qCmrWp2PocVBqba4Qt/f71r2fEsHWJ9wPdkSD+ax6/sOIs4uN5zcQ/h33UoSNFYPKiEC2MOb9IMV/vfEpYrQcwEkFhkMY2vbzzeCpdptL8sZHybUM="
    local-dir: docs/_site
    target-branch: gh-pages
    keep-history: false
    skip-cleanup: true
    on:
      branch: master
